"""Build version registries from reports generated by an official server jar."""

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def _load(path):
    return json.loads(path.read_text(encoding="utf-8"))


def _write(path, value):
    path.write_text(
        json.dumps(value, separators=(",", ":"), sort_keys=True) + "\n",
        encoding="utf-8",
    )


def _registry_ids(registries, registry):
    entries = registries[f"minecraft:{registry}"]["entries"]
    return {
        name.removeprefix("minecraft:"): entry["protocol_id"]
        for name, entry in entries.items()
    }


def _remap_items(base, ids):
    by_name = {entry["name"]: entry for entry in base}
    result = []
    for name, item_id in sorted(ids.items(), key=lambda pair: pair[1]):
        entry = dict(by_name.get(name, {
            "displayName": name.replace("_", " ").title(),
            "name": name,
            "stackSize": 64,
        }))
        entry["id"] = item_id
        result.append(entry)
    return result


def _remap_entities(base, ids):
    by_name = {entry["name"]: entry for entry in base}
    result = []
    for name, entity_id in sorted(ids.items(), key=lambda pair: pair[1]):
        entry = dict(by_name.get(name, {
            "displayName": name.replace("_", " ").title(),
            "name": name,
            "type": "other",
            "width": 0.6,
            "height": 1.8,
        }))
        entry["id"] = entity_id
        entry["internalId"] = entity_id
        result.append(entry)
    return result


def _remap_blocks(base, ids, report, item_ids):
    by_name = {entry["name"]: entry for entry in base}
    old_item_names = {
        entry["id"]: entry["name"]
        for entry in _load(ROOT / "items" / "items_26.1.json")
    }
    result = []
    for name, block_id in sorted(ids.items(), key=lambda pair: pair[1]):
        states = report[name]["states"]
        state_ids = [state["id"] for state in states]
        entry = dict(by_name.get(name, {
            "boundingBox": "block", "diggable": True,
            "displayName": name.replace("_", " ").title(), "drops": [],
            "emitLight": 0, "filterLight": 15, "hardness": 0,
            "material": "default", "name": name, "resistance": 0,
            "stackSize": 64, "states": [], "transparent": False,
        }))
        entry.update({
            "id": block_id,
            "minStateId": min(state_ids),
            "maxStateId": max(state_ids),
            "defaultState": next(
                state["id"] for state in states if state.get("default", False)
            ),
        })
        entry["drops"] = [
            item_ids[old_item_names[drop]]
            for drop in entry.get("drops", [])
            if drop in old_item_names and old_item_names[drop] in item_ids
        ]
        entry["harvestTools"] = {
            str(item_ids[old_item_names[int(tool)]]): enabled
            for tool, enabled in entry.get("harvestTools", {}).items()
            if int(tool) in old_item_names and old_item_names[int(tool)] in item_ids
        }
        result.append(entry)
    return result


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("reports", type=Path)
    parser.add_argument("--version", required=True)
    parser.add_argument("--base", default="26.1")
    args = parser.parse_args(argv)

    registries = _load(args.reports / "registries.json")
    block_report = {
        name.removeprefix("minecraft:"): value
        for name, value in _load(args.reports / "blocks.json").items()
    }
    item_ids = _registry_ids(registries, "item")
    entity_ids = _registry_ids(registries, "entity_type")
    block_ids = _registry_ids(registries, "block")

    items = _remap_items(
        _load(ROOT / "items" / f"items_{args.base}.json"), item_ids
    )
    entities = _remap_entities(
        _load(ROOT / "entities" / f"entities_{args.base}.json"), entity_ids
    )
    blocks = _remap_blocks(
        _load(ROOT / "blocks" / f"blocks_{args.base}.json"),
        block_ids, block_report, item_ids,
    )
    _write(ROOT / "items" / f"items_{args.version}.json", items)
    _write(ROOT / "entities" / f"entities_{args.version}.json", entities)
    _write(ROOT / "blocks" / f"blocks_{args.version}.json", blocks)


if __name__ == "__main__":
    main()
